const {createClient}=window.supabase;const db=createClient(APP_CONFIG.SUPABASE_URL,APP_CONFIG.SUPABASE_ANON_KEY);const $=id=>document.getElementById(id);let role=null;const MIN_DONATION_GAP_MONTHS=3;
function parseDate(v){if(!v)return null;const [y,m,d]=String(v).slice(0,10).split('-').map(Number);return y&&m&&d?new Date(y,m-1,d):null}
function addMonths(date,months){const day=date.getDate();const d=new Date(date.getFullYear(),date.getMonth(),1);d.setMonth(d.getMonth()+months);const last=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();d.setDate(Math.min(day,last));return d}
function effectiveAvailable(x){if(!x.available)return false;const d=parseDate(x.last_donation);if(!d)return true;const e=addMonths(d,MIN_DONATION_GAP_MONTHS);const t=new Date();const today=new Date(t.getFullYear(),t.getMonth(),t.getDate());return e<=today}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function msg(text,ok=false){$('dashMsg').textContent=text;$('dashMsg').className=`notice ${ok?'success':''}`}
function loginMsg(text){$('loginMsg').textContent=text;$('loginMsg').classList.remove('hidden')}
async function getRole(){const {data,error}=await db.from('staff').select('role').maybeSingle();if(error||!data)return null;return data.role}
async function refresh(){const {data,error}=await db.from('donors').select('*').order('created_at',{ascending:false});if(error){msg(error.message);return}const d=data||[];$('total').textContent=d.length;$('available').textContent=d.filter(effectiveAvailable).length;$('unavailable').textContent=d.filter(x=>!effectiveAvailable(x)).length;$('donorRows').innerHTML=d.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.blood_group)}</td><td>${effectiveAvailable(x)?'🟢':'🔴'}</td><td>${esc(x.city||'')} — ${esc(x.location||'')}</td><td><button class="secondary" onclick="editDonor(${x.id})">Edit</button> <button class="secondary danger" onclick="deleteDonor(${x.id})">Delete</button></td></tr>`).join('')}
window.editDonor=async id=>{const {data}=await db.from('donors').select('*').eq('id',id).single();if(!data)return;$('donorId').value=data.id;$('name').value=data.name;$('blood').value=data.blood_group;$('city').value=data.city||'Dhaka';$('location').value=data.location||'';$('available').value=String(data.available);$('lastDonation').value=data.last_donation||'';$('verified').value=data.verified_at||'';$('phone').value=data.phone||'';$('formTitle').textContent='Edit donor';$('cancelEdit').classList.remove('hidden');scrollTo({top:0,behavior:'smooth'})}
window.deleteDonor=async id=>{if(!confirm('Delete this donor?'))return;const {error}=await db.from('donors').delete().eq('id',id);if(error)msg(error.message);else{msg('Donor deleted.',true);refresh()}}
$('login').onclick=async()=>{const {error}=await db.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error){loginMsg(error.message);return}init()};$('logout').onclick=async()=>{await db.auth.signOut();location.reload()};
$('saveDonor').onclick=async()=>{const payload={name:$('name').value.trim(),blood_group:$('blood').value,available:$('available').value==='true',city:$('city').value,location:$('location').value.trim(),last_donation:$('lastDonation').value||null,verified_at:$('verified').value||null,phone:$('phone').value.trim()||null};if(!payload.name||!payload.location){msg('Name and specific location are required.');return}const id=$('donorId').value;const res=id?await db.from('donors').update(payload).eq('id',id):await db.from('donors').insert(payload);if(res.error)msg(res.error.message);else{msg(id?'Donor updated.':'Donor added.',true);clearForm();refresh()}};$('cancelEdit').onclick=clearForm;
function clearForm(){$('donorId').value='';$('name').value='';$('city').value='Dhaka';$('location').value='';$('lastDonation').value='';$('verified').value=new Date().toISOString().slice(0,10);$('phone').value='';$('formTitle').textContent='Add donor';$('cancelEdit').classList.add('hidden')}
async function loadStaff(){const {data,error}=await db.from('staff').select('*').order('created_at',{ascending:true});if(error){msg(error.message);return}$('staffRows').innerHTML=(data||[]).map(x=>`<tr><td>${esc(x.user_id)}</td><td>${esc(x.role)}</td><td><button class="secondary danger" onclick="removeStaff('${x.user_id}')">Remove</button></td></tr>`).join('')}
window.removeStaff=async uid=>{if(!confirm('Remove this staff member?'))return;const {error}=await db.from('staff').delete().eq('user_id',uid);if(error)msg(error.message);else{msg('Staff removed.',true);loadStaff()}};$('addStaff').onclick=async()=>{const uid=$('staffUserId').value.trim(),r=$('staffRole').value;if(!uid){msg('Enter a Supabase Auth User ID.');return}const {error}=await db.from('staff').insert({user_id:uid,role:r});if(error)msg(error.message);else{msg('Staff added.',true);$('staffUserId').value='';loadStaff()}};
async function init(){const {data:{session}}=await db.auth.getSession();if(!session){$('loginBox').classList.remove('hidden');$('dashboard').classList.add('hidden');return}role=await getRole();if(!role){await db.auth.signOut();loginMsg('This account is not authorized.');return}$('loginBox').classList.add('hidden');$('dashboard').classList.remove('hidden');$('logout').classList.remove('hidden');$('verified').value=new Date().toISOString().slice(0,10);await refresh();if(role==='admin'){$('staffBox').classList.remove('hidden');await loadStaff()}}db.auth.onAuthStateChange(()=>{});init();
