const { createClient } = window.supabase;
const db = createClient(APP_CONFIG.SUPABASE_URL, APP_CONFIG.SUPABASE_ANON_KEY);
const $ = id => document.getElementById(id);
const MIN_DONATION_GAP_MONTHS = 3;
let donors = [];
function parseDate(v){if(!v)return null;const [y,m,d]=String(v).slice(0,10).split('-').map(Number);return y&&m&&d?new Date(y,m-1,d):null}
function addMonths(date, months){const day=date.getDate();const d=new Date(date.getFullYear(),date.getMonth(),1);d.setMonth(d.getMonth()+months);const last=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();d.setDate(Math.min(day,last));return d}
function today(){const d=new Date();return new Date(d.getFullYear(),d.getMonth(),d.getDate())}
function eligibilityDate(lastDonation){const d=parseDate(lastDonation);return d?addMonths(d,MIN_DONATION_GAP_MONTHS):null}
function effectiveAvailable(x){if(!x.available)return false;const e=eligibilityDate(x.last_donation);return !e||e<=today()}
function fmtDate(v){const d=parseDate(v);return d?d.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}):'Not specified'}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
async function load(){const {data,error}=await db.from('donors').select('id,name,blood_group,available,city,location,last_donation,verified_at,phone').order('available',{ascending:false}).order('verified_at',{ascending:false});if(error){console.error(error);donors=[];return}donors=data||[]}
function render(){let d=[...donors],b=$('blood').value,city=$('city').value,l=$('location').value.trim().toLowerCase(),s=$('status').value,sort=$('sort').value;if(b)d=d.filter(x=>x.blood_group===b);if(city)d=d.filter(x=>(x.city||'').toLowerCase()===city.toLowerCase());if(l)d=d.filter(x=>(x.location||'').toLowerCase().includes(l));if(s)d=d.filter(x=>s==='available'?effectiveAvailable(x):!effectiveAvailable(x));if(sort==='available')d.sort((a,b)=>Number(effectiveAvailable(b))-Number(effectiveAvailable(a)));if(sort==='blood')d.sort((a,b)=>a.blood_group.localeCompare(b.blood_group));if(sort==='location')d.sort((a,b)=>`${a.city||''} ${a.location||''}`.localeCompare(`${b.city||''} ${b.location||''}`));if(sort==='recent')d.sort((a,b)=>String(b.verified_at||'').localeCompare(String(a.verified_at||'')));$('count').textContent=`${d.length} donor${d.length===1?'':'s'}`;$('results').innerHTML=d.length?d.map(x=>{const ok=effectiveAvailable(x),e=eligibilityDate(x.last_donation),cooldown=x.available&&e&&e>today();return `<article class="card"><div class="card-top"><div class="name">${esc(x.name)}</div><div class="blood">${esc(x.blood_group)}</div></div><span class="badge ${ok?'yes':'no'}">${ok?'🟢 Available':'🔴 Unavailable'}</span><div class="meta">📍 ${esc(x.city||'Not specified')}${x.location?` — ${esc(x.location)}`:''}<br>🩸 Last donation: ${esc(fmtDate(x.last_donation))}${cooldown?`<br>⏳ Available from: ${esc(fmtDate(e))}`:''}<br>✓ Verified: ${esc(fmtDate(x.verified_at))}</div>${x.phone?`<a class="contact" href="tel:${encodeURIComponent(x.phone)}">Contact donor</a>`:''}</article>`}).join(''):`<div class="card"><strong>No donors found.</strong><div class="meta">Try another filter.</div></div>`}
['blood','city','location','status','sort'].forEach(id=>$(id).addEventListener('input',render));
(async()=>{await load();render()})();
